# Generated by Django 4.0.3 on 2024-03-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_stu_id_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('dept_HOD', models.CharField(max_length=50)),
                ('staff_count', models.IntegerField()),
                ('Tot_sub', models.IntegerField()),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_code', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_duration', models.FloatField()),
                ('Tot_marks', models.FloatField()),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
            options={
                'db_table': 'Examination',
            },
        ),
    ]
