# Generated by Django 4.0.3 on 2024-03-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_department_subject_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='sub_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
