# Generated by Django 4.0.3 on 2024-03-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_examination_sub_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_dept',
        ),
        migrations.AlterField(
            model_name='examination',
            name='Tot_marks',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exam_duration',
            field=models.FloatField(default=180),
        ),
        migrations.AlterField(
            model_name='examination',
            name='sub_name',
            field=models.CharField(max_length=50),
        ),
    ]
