# Generated by Django 4.0.3 on 2024-03-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_stu_dept_alter_examination_tot_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.department'),
        ),
    ]
