# Generated by Django 4.0.3 on 2024-03-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_stu_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_sub', models.CharField(max_length=50)),
                ('stu_marks', models.IntegerField()),
            ],
            options={
                'db_table': 'marks',
            },
        ),
    ]
