# Generated by Django 4.0.3 on 2024-03-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_marks_stu_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='stu_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
        ),
    ]
