# Generated by Django 4.0.3 on 2024-03-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_marks_stu_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='stu_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
    ]
