# Generated by Django 4.0.3 on 2024-03-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_marks_stu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='stu_sub',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
